### ISSUE TITLE
about BLFont question

### ISSUE THREAD

**Issue by HowToExpect** [blend2d/blend2d#187]
[Blend2D] ASSERTION FAILURE: 'mCtx.aheadGlyphCount >= inputGlyphCount + lookaheadGlyphCount' at 'F:\build\blend2d\src\blend2d\opentype\otlayout.cpp' [line 1393]

`struct Painter {
	BLContext	ctx;
};

void drawText(Painter* painter, BLFont& font, const std::string& text, int x, int y)
{
	painter->ctx.setFillStyle(BLRgba32(0xFFFFFFFF));

	BLFontMetrics fm = font.metrics();
	BLGlyphBuffer gb;
	gb.setUtf8Text(text.c_str());

	font.shape(gb);

	int ypos = y + fm.ascent;

	BLPointI p(x, ypos);
	painter->ctx.fillGlyphRun(p, font, gb.glyphRun());
}

int main()
{
	int w = 1280;
	int h = 720;

	Painter* painter = new Painter;

	BLImage	blImage(w, h, BL_FORMAT_PRGB32);
	painter->ctx = BLContext(blImage);

	BLFontFace face;
	BLFont font;

	face.createFromFile("SourceHanSansSC-Medium.otf");
	font.createFromFace(face, 28);

	painter->ctx.clearAll();
	painter->ctx.setFillStyle(BLRgba32(0xFF000000));
	painter->ctx.fillRect(0, 0, 1280, 720);

	std::string str = "1234";

	drawText(painter, font, str, 100, 100);
}`

If str="12345" will be displayed normally, str="1234" will report this error.

**Comment by kobalicek** [comment]
Please can you send me the font, or add where I can download it? Thanks!

**Comment by HowToExpect** [comment]
this is fonts

**Comment by HowToExpect** [comment]
[Uploading fonts.zip…]()
this is fonts

**Comment by kobalicek** [comment]
The link is not correct, please just paste the font file to GH it should upload it.

**Comment by HowToExpect** [comment]
[fonts.zip](https://github.com/blend2d/blend2d/files/13558266/fonts.zip)

**Comment by HowToExpect** [comment]
Some fonts can be displayed normally

**Comment by HowToExpect** [comment]
[fonts1.zip](https://github.com/blend2d/blend2d/files/13558280/fonts1.zip)
this fonts can be displayed normally

**Comment by dongzhong** [comment]
@kobalicek I have the similar problem.

```cpp
BLGlyphBuffer glyph_buffer;
BLTextMetrics text_metrics;
  
while (p_start < text.size() && p_end <= text.length()) {
  const auto sub_text = text.substr(p_start, p_end);

  glyph_buffer.setUtf8Text((sub_text).c_str(), p_end - p_start);

  BLResult result = bl_font_->shape(glyph_buffer); // When for the 4th char, the same assert occurs.
  bl_font_->getTextMetrics(glyph_buffer, text_metrics);

  // .......
}
```

**Comment by HowToExpect** [comment]
This problem is related to the font. I changed it to another font and it was fine. However, there was no problem with the previous version. This problem only appeared after updating to the latest version.

**Comment by kobalicek** [comment]
I need some time to actually check this one out. If it hits an assert it means there is a bug in the font pipeline. If it's easily reproducible I will fix that soon.

**Comment by HowToExpect** [comment]
This problem is bound to occur. Will this problem be fixed soon?

**Comment by kobalicek** [comment]
Sorry for waiting too long for this one-line fix!

The problem should be fixed by https://github.com/blend2d/blend2d/commit/235997a8f829f54b56925c7332b8f0bc5b49bcf6 - it would be nice to get a confirmation.

**Comment by HowToExpect** [comment]
I verified that both window and linux can run normally, thank you very much

**Comment by kobalicek** [comment]
Thanks a lot for the report!

**Comment by ThereGoesMySanity** [comment]
Looks like the same bug still exists in `applyGSubLookupType8Format1` and `applyGPosLookupType8Format3`.

https://github.com/blend2d/blend2d/blob/16088c4ffb41813d9f0511fb2a6896f5608a4706/src/blend2d/opentype/otlayout.cpp#L2245

https://github.com/blend2d/blend2d/blob/16088c4ffb41813d9f0511fb2a6896f5608a4706/src/blend2d/opentype/otlayout.cpp#L3035
